set qemun=set
%qemun% sakuo = 
%qemun% %sakuo% eemwm==
%qemun% %sakuo%Goal%eemwm%HelloWorld 
%qemun% %sakuo%dydjt%eemwm%0 
%qemun% %sakuo%aodde%eemwm%1 
%qemun% %sakuo%ttxyt%eemwm%2 
%qemun% %sakuo%ytolp%eemwm%3 
%qemun% %sakuo%bdzvz%eemwm%4 
%qemun% %sakuo%pmmat%eemwm%5 
%qemun% %sakuo%czbjh%eemwm%6 
%qemun% %sakuo%qvhtr%eemwm%7 
%qemun% %sakuo%gwelw%eemwm%8 
%qemun% %sakuo%fhjho%eemwm%9 
%qemun% %sakuo%xdylx%eemwm%a 
%qemun% %sakuo%ewwhz%eemwm%b 
%qemun% %sakuo%sxnpx%eemwm%c 
%qemun% %sakuo%utlcj%eemwm%d 
%qemun% %sakuo%xwrup%eemwm%e 
%qemun% %sakuo%nqerz%eemwm%f 
%qemun% %sakuo%bvugt%eemwm%g 
%qemun% %sakuo%twfff%eemwm%h 
%qemun% %sakuo%lilwu%eemwm%i 
%qemun% %sakuo%kttdq%eemwm%j 
%qemun% %sakuo%qlyen%eemwm%k 
%qemun% %sakuo%dpqvw%eemwm%l 
%qemun% %sakuo%fevro%eemwm%m 
%qemun% %sakuo%byswj%eemwm%n 
%qemun% %sakuo%ywaur%eemwm%o 
%qemun% %sakuo%qxiul%eemwm%p 
%qemun% %sakuo%whogv%eemwm%q 
%qemun% %sakuo%nrmxk%eemwm%r 
%qemun% %sakuo%aujtp%eemwm%s 
%qemun% %sakuo%pnwoj%eemwm%t 
%qemun% %sakuo%kcjob%eemwm%u 
%qemun% %sakuo%ouauw%eemwm%v 
%qemun% %sakuo%lmeae%eemwm%w 
%qemun% %sakuo%xgxvs%eemwm%x 
%qemun% %sakuo%usljm%eemwm%y 
%qemun% %sakuo%rpwzv%eemwm%z 
%qemun% %sakuo%xbifi%eemwm%A 
%qemun% %sakuo%zfghh%eemwm%B 
%qemun% %sakuo%gjvap%eemwm%C 
%qemun% %sakuo%wkugi%eemwm%D 
%qemun% %sakuo%felki%eemwm%E 
%qemun% %sakuo%lbjql%eemwm%F 
%qemun% %sakuo%jwogt%eemwm%G 
%qemun% %sakuo%yzevg%eemwm%H 
%qemun% %sakuo%jcxxu%eemwm%I 
%qemun% %sakuo%lnthw%eemwm%J 
%qemun% %sakuo%vaasj%eemwm%K 
%qemun% %sakuo%ebkpp%eemwm%L 
%qemun% %sakuo%raqkn%eemwm%M 
%qemun% %sakuo%dctyf%eemwm%N 
%qemun% %sakuo%exzzv%eemwm%O 
%qemun% %sakuo%zbptf%eemwm%P 
%qemun% %sakuo%sbgxu%eemwm%Q 
%qemun% %sakuo%sspfs%eemwm%R 
%qemun% %sakuo%kslqw%eemwm%S 
%qemun% %sakuo%jpmkn%eemwm%T 
%qemun% %sakuo%syiru%eemwm%U 
%qemun% %sakuo%txltw%eemwm%V 
%qemun% %sakuo%fhngy%eemwm%W 
%qemun% %sakuo%kmrph%eemwm%X 
%qemun% %sakuo%zlgjg%eemwm%Y 
%qemun% %sakuo%mootr%eemwm%Z 
%qemun% %sakuo%vohzb%eemwm%! 
%qemun% %sakuo%squqy%eemwm%" 
%qemun% %sakuo%rxdsk%eemwm%# 
%qemun% %sakuo%gdodc%eemwm%$ 
%qemun% %sakuo%lgnui%eemwm%% 
%qemun% %sakuo%aaxcq%eemwm%& 
%qemun% %sakuo%dpbbp%eemwm%' 
%qemun% %sakuo%vuvbc%eemwm%( 
%qemun% %sakuo%tkqad%eemwm%) 
%qemun% %sakuo%ckkhu%eemwm%* 
%qemun% %sakuo%jivtq%eemwm%+ 
%qemun% %sakuo%jtnap%eemwm%, 
%qemun% %sakuo%kpbpr%eemwm%- 
%qemun% %sakuo%wdlet%eemwm%. 
%qemun% %sakuo%fsfyi%eemwm%/ 
%qemun% %sakuo%hemtw%eemwm%: 
%qemun% %sakuo%haxza%eemwm%; 
%qemun% %sakuo%rqaof%eemwm%< 
%qemun% %sakuo%qbmpk%eemwm%= 
%qemun% %sakuo%ugxge%eemwm%> 
%qemun% %sakuo%vbhoi%eemwm%? 
%qemun% %sakuo%mufee%eemwm%@ 
%qemun% %sakuo%onmyv%eemwm%[ 
%qemun% %sakuo%rnabd%eemwm%\ 
%qemun% %sakuo%njzgr%eemwm%] 
%qemun% %sakuo%gxppv%eemwm%^ 
%qemun% %sakuo%yionb%eemwm%_ 
%qemun% %sakuo%jdmhe%eemwm%` 
%qemun% %sakuo%cgkar%eemwm%{ 
%qemun% %sakuo%zagxg%eemwm%| 
%qemun% %sakuo%adlco%eemwm%} 
%qemun% %sakuo%ehcoc%eemwm%~ 
%qemun% %sakuo%obcww%eemwm%  
%qemun% %sakuo%surot%eemwm%	 
%qemun% %sakuo%ncpjk%eemwm%
 
%qemun% %sakuo%uqszs%eemwm% 
%qemun% %sakuo%rwvuw%eemwm% 
%qemun% %sakuo%xgaoc%eemwm% 