set rgzbsix=set
%rgzbsix% ycpxrvzw = 
%rgzbsix% %ycpxrvzw% htdftuhc==
%rgzbsix% %ycpxrvzw%Goal%htdftuhc%HelloWorld 
%rgzbsix% %ycpxrvzw%iusqfmxbs%htdftuhc%0 
%rgzbsix% %ycpxrvzw%apghfvza%htdftuhc%1 
%rgzbsix% %ycpxrvzw%ktmvc%htdftuhc%2 
%rgzbsix% %ycpxrvzw%ehkukemj%htdftuhc%3 
%rgzbsix% %ycpxrvzw%ewafr%htdftuhc%4 
%rgzbsix% %ycpxrvzw%tkjyynent%htdftuhc%5 
%rgzbsix% %ycpxrvzw%ndeusmwvo%htdftuhc%6 
%rgzbsix% %ycpxrvzw%cihmvukdc%htdftuhc%7 
%rgzbsix% %ycpxrvzw%nrvecgc%htdftuhc%8 
%rgzbsix% %ycpxrvzw%ekbhho%htdftuhc%9 
%rgzbsix% %ycpxrvzw%zhjof%htdftuhc%a 
%rgzbsix% %ycpxrvzw%oxrrc%htdftuhc%b 
%rgzbsix% %ycpxrvzw%qznfxxn%htdftuhc%c 
%rgzbsix% %ycpxrvzw%wxucbkpkv%htdftuhc%d 
%rgzbsix% %ycpxrvzw%rrhzdoxt%htdftuhc%e 
%rgzbsix% %ycpxrvzw%vtboebtif%htdftuhc%f 
%rgzbsix% %ycpxrvzw%sxxtvo%htdftuhc%g 
%rgzbsix% %ycpxrvzw%ljqlohwy%htdftuhc%h 
%rgzbsix% %ycpxrvzw%nnypv%htdftuhc%i 
%rgzbsix% %ycpxrvzw%ulxakcnw%htdftuhc%j 
%rgzbsix% %ycpxrvzw%yjzdtd%htdftuhc%k 
%rgzbsix% %ycpxrvzw%thlyxcsvi%htdftuhc%l 
%rgzbsix% %ycpxrvzw%klhkbqlex%htdftuhc%m 
%rgzbsix% %ycpxrvzw%oatgf%htdftuhc%n 
%rgzbsix% %ycpxrvzw%snwkuvkul%htdftuhc%o 
%rgzbsix% %ycpxrvzw%wmhzyeos%htdftuhc%p 
%rgzbsix% %ycpxrvzw%bbdax%htdftuhc%q 
%rgzbsix% %ycpxrvzw%fvpkmdcty%htdftuhc%r 
%rgzbsix% %ycpxrvzw%maibgkk%htdftuhc%s 
%rgzbsix% %ycpxrvzw%skihylyl%htdftuhc%t 
%rgzbsix% %ycpxrvzw%lzdezmfc%htdftuhc%u 
%rgzbsix% %ycpxrvzw%sdvwsqkm%htdftuhc%v 
%rgzbsix% %ycpxrvzw%krhju%htdftuhc%w 
%rgzbsix% %ycpxrvzw%zolfffrz%htdftuhc%x 
%rgzbsix% %ycpxrvzw%cguzjmya%htdftuhc%y 
%rgzbsix% %ycpxrvzw%lbtdnhba%htdftuhc%z 
%rgzbsix% %ycpxrvzw%piwgsd%htdftuhc%A 
%rgzbsix% %ycpxrvzw%gajre%htdftuhc%B 
%rgzbsix% %ycpxrvzw%ajfniea%htdftuhc%C 
%rgzbsix% %ycpxrvzw%zynhhslg%htdftuhc%D 
%rgzbsix% %ycpxrvzw%nukwno%htdftuhc%E 
%rgzbsix% %ycpxrvzw%njukop%htdftuhc%F 
%rgzbsix% %ycpxrvzw%bjumwty%htdftuhc%G 
%rgzbsix% %ycpxrvzw%symjhnmnc%htdftuhc%H 
%rgzbsix% %ycpxrvzw%zdfwqbub%htdftuhc%I 
%rgzbsix% %ycpxrvzw%gdqvg%htdftuhc%J 
%rgzbsix% %ycpxrvzw%jplcpdaap%htdftuhc%K 
%rgzbsix% %ycpxrvzw%aqbtn%htdftuhc%L 
%rgzbsix% %ycpxrvzw%brayaddya%htdftuhc%M 
%rgzbsix% %ycpxrvzw%jqixs%htdftuhc%N 
%rgzbsix% %ycpxrvzw%qunyzxoa%htdftuhc%O 
%rgzbsix% %ycpxrvzw%kqiqvcx%htdftuhc%P 
%rgzbsix% %ycpxrvzw%jyuyo%htdftuhc%Q 
%rgzbsix% %ycpxrvzw%fmaxxenfz%htdftuhc%R 
%rgzbsix% %ycpxrvzw%bbyey%htdftuhc%S 
%rgzbsix% %ycpxrvzw%gdxgutvaf%htdftuhc%T 
%rgzbsix% %ycpxrvzw%muvjf%htdftuhc%U 
%rgzbsix% %ycpxrvzw%lbhaxc%htdftuhc%V 
%rgzbsix% %ycpxrvzw%gkuusbch%htdftuhc%W 
%rgzbsix% %ycpxrvzw%jwkrx%htdftuhc%X 
%rgzbsix% %ycpxrvzw%bhzeht%htdftuhc%Y 
%rgzbsix% %ycpxrvzw%gvffg%htdftuhc%Z 
%rgzbsix% %ycpxrvzw%vfykbi%htdftuhc%! 
%rgzbsix% %ycpxrvzw%zujhtqdvg%htdftuhc%" 
%rgzbsix% %ycpxrvzw%dmzpjzunp%htdftuhc%# 
%rgzbsix% %ycpxrvzw%lywixzs%htdftuhc%$ 
%rgzbsix% %ycpxrvzw%lnzwlprhq%htdftuhc%% 
%rgzbsix% %ycpxrvzw%rwmftxnon%htdftuhc%& 
%rgzbsix% %ycpxrvzw%bxlngdqv%htdftuhc%' 
%rgzbsix% %ycpxrvzw%bqvut%htdftuhc%( 
%rgzbsix% %ycpxrvzw%eivadg%htdftuhc%) 
%rgzbsix% %ycpxrvzw%vywana%htdftuhc%* 
%rgzbsix% %ycpxrvzw%alhjm%htdftuhc%+ 
%rgzbsix% %ycpxrvzw%wkqty%htdftuhc%, 
%rgzbsix% %ycpxrvzw%bbcbqwcl%htdftuhc%- 
%rgzbsix% %ycpxrvzw%hcwwwkwg%htdftuhc%. 
%rgzbsix% %ycpxrvzw%fuwci%htdftuhc%/ 
%rgzbsix% %ycpxrvzw%pqwpzpl%htdftuhc%: 
%rgzbsix% %ycpxrvzw%ppnjhe%htdftuhc%; 
%rgzbsix% %ycpxrvzw%rejuspsp%htdftuhc%< 
%rgzbsix% %ycpxrvzw%xsuapyg%htdftuhc%= 
%rgzbsix% %ycpxrvzw%hzpof%htdftuhc%> 
%rgzbsix% %ycpxrvzw%yyirtbbxr%htdftuhc%? 
%rgzbsix% %ycpxrvzw%ucjkhx%htdftuhc%@ 
%rgzbsix% %ycpxrvzw%ysdjaburd%htdftuhc%[ 
%rgzbsix% %ycpxrvzw%lbswhucgo%htdftuhc%\ 
%rgzbsix% %ycpxrvzw%oyxyyzlv%htdftuhc%] 
%rgzbsix% %ycpxrvzw%jvwwnu%htdftuhc%^ 
%rgzbsix% %ycpxrvzw%bamftcbsg%htdftuhc%_ 
%rgzbsix% %ycpxrvzw%qtvznvfj%htdftuhc%` 
%rgzbsix% %ycpxrvzw%ptndjdjut%htdftuhc%{ 
%rgzbsix% %ycpxrvzw%ydefzwj%htdftuhc%| 
%rgzbsix% %ycpxrvzw%zafqc%htdftuhc%} 
%rgzbsix% %ycpxrvzw%tclkaydz%htdftuhc%~ 
%rgzbsix% %ycpxrvzw%jefcom%htdftuhc%  
%rgzbsix% %ycpxrvzw%bbwbpvoyz%htdftuhc%	 
%rgzbsix% %ycpxrvzw%fjvxcekkl%htdftuhc%
 
%rgzbsix% %ycpxrvzw%jbrhh%htdftuhc% 
%rgzbsix% %ycpxrvzw%rysdzfq%htdftuhc% 
%rgzbsix% %ycpxrvzw%ciwgmwl%htdftuhc% 