set kj=set
%kj% cg = 
%kj% %cg% zy==
%kj% %cg%DummyName%zy%HelloWorld 
%kj% %cg%sn%zy%0 
%kj% %cg%hp%zy%1 
%kj% %cg%ay%zy%2 
%kj% %cg%ee%zy%3 
%kj% %cg%rk%zy%4 
%kj% %cg%ry%zy%5 
%kj% %cg%yq%zy%6 
%kj% %cg%nd%zy%7 
%kj% %cg%gx%zy%8 
%kj% %cg%kz%zy%9 
%kj% %cg%nv%zy%a 
%kj% %cg%kc%zy%b 
%kj% %cg%xv%zy%c 
%kj% %cg%ed%zy%d 
%kj% %cg%xh%zy%e 
%kj% %cg%wm%zy%f 
%kj% %cg%mx%zy%g 
%kj% %cg%mt%zy%h 
%kj% %cg%ui%zy%i 
%kj% %cg%rn%zy%j 
%kj% %cg%xe%zy%k 
%kj% %cg%xc%zy%l 
%kj% %cg%pf%zy%m 
%kj% %cg%ks%zy%n 
%kj% %cg%zw%zy%o 
%kj% %cg%rs%zy%p 
%kj% %cg%ok%zy%q 
%kj% %cg%xl%zy%r 
%kj% %cg%rr%zy%s 
%kj% %cg%kp%zy%t 
%kj% %cg%oa%zy%u 
%kj% %cg%ef%zy%v 
%kj% %cg%wp%zy%w 
%kj% %cg%zo%zy%x 
%kj% %cg%mj%zy%y 
%kj% %cg%rf%zy%z 
%kj% %cg%jo%zy%A 
%kj% %cg%vi%zy%B 
%kj% %cg%xq%zy%C 
%kj% %cg%eo%zy%D 
%kj% %cg%hi%zy%E 
%kj% %cg%wx%zy%F 
%kj% %cg%cb%zy%G 
%kj% %cg%ct%zy%H 
%kj% %cg%ou%zy%I 
%kj% %cg%nu%zy%J 
%kj% %cg%io%zy%K 
%kj% %cg%rw%zy%L 
%kj% %cg%up%zy%M 
%kj% %cg%ow%zy%N 
%kj% %cg%ne%zy%O 
%kj% %cg%di%zy%P 
%kj% %cg%uq%zy%Q 
%kj% %cg%wa%zy%R 
%kj% %cg%bo%zy%S 
%kj% %cg%re%zy%T 
%kj% %cg%rx%zy%U 
%kj% %cg%jn%zy%V 
%kj% %cg%ha%zy%W 
%kj% %cg%xt%zy%X 
%kj% %cg%ab%zy%Y 
%kj% %cg%er%zy%Z 
%kj% %cg%ya%zy%! 
%kj% %cg%wc%zy%" 
%kj% %cg%jl%zy%# 
%kj% %cg%eq%zy%$ 
%kj% %cg%lq%zy%% 
%kj% %cg%rb%zy%& 
%kj% %cg%sz%zy%' 
%kj% %cg%mh%zy%( 
%kj% %cg%un%zy%) 
%kj% %cg%gu%zy%* 
%kj% %cg%qj%zy%+ 
%kj% %cg%ij%zy%, 
%kj% %cg%th%zy%- 
%kj% %cg%kr%zy%. 
%kj% %cg%rp%zy%/ 
%kj% %cg%zd%zy%: 
%kj% %cg%ch%zy%; 
%kj% %cg%xb%zy%< 
%kj% %cg%qf%zy%= 
%kj% %cg%bv%zy%> 
%kj% %cg%uh%zy%? 
%kj% %cg%zq%zy%@ 
%kj% %cg%vp%zy%[ 
%kj% %cg%pg%zy%\ 
%kj% %cg%mo%zy%] 
%kj% %cg%hu%zy%^ 
%kj% %cg%jk%zy%_ 
%kj% %cg%ci%zy%` 
%kj% %cg%ds%zy%{ 
%kj% %cg%qo%zy%| 
%kj% %cg%lz%zy%} 
%kj% %cg%mm%zy%~ 
%kj% %cg%bh%zy%  
%kj% %cg%ag%zy%	 
%kj% %cg%zk%zy%
 
%kj% %cg%mr%zy% 
%kj% %cg%yk%zy% 
%kj% %cg%it%zy% 